### ISSUE TITLE
The kv table indexes need a prefix index on meta_value(64)

### ISSUE THREAD

**Issue by OllieJones** [OllieJones/index-wp-mysql-for-speeed#2]
See this. https://wordpress.org/support/topic/key-changes-slowed-down-postmeta-lookup/

Queries like 

`SELECT DISTINCT p1.post_id
FROM wp_postmeta p1
WHERE p1.meta_value LIKE 'koolen%'
AND p1.meta_key IN ('_billing_last_name')`

need help.  This key

`ALTER TABLE wp_postmeta DROP KEY meta_key,  ADD KEY meta_key (meta_key, meta_value(64), post_id);`

gives that help.

**Comment by OllieJones** [comment]
The thing is, we'll need to be able to "upgrade" a high-performance index in the field. That will be more comfortable for users than reverting it first. That will take some "how to get there from here" logic in the index creation.

**Comment by OllieJones** [comment]
See #5  for the dependency. The indexes now,
Barracuda:
		
```
ADD UNIQUE KEY meta_id (meta_id)
ADD PRIMARY KEY (post_id, meta_key, meta_id)
ADD KEY meta_key (meta_key, meta_value(32), post_id)
ADD KEY meta_value (meta_value(32), meta_key, post_id)
```


Antelope:

```
ADD UNIQUE KEY meta_id (meta_id)
ADD PRIMARY KEY (post_id, meta_id)
ADD KEY post_id (post_id, meta_key(32), meta_value(32))
ADD KEY meta_key (meta_key(32), meta_value(32), post_id)
ADD KEY meta_value (meta_value(32), meta_key(32), post_id)
```

**Comment by rjasdf** [comment]
If the usage of an index can't get beyond a prefix, then:

Barracuda:

ADD UNIQUE KEY meta_id (meta_id)
ADD PRIMARY KEY (post_id, meta_key, meta_id)
ADD KEY meta_key (meta_key, meta_value(32))
ADD KEY meta_value (meta_value(32))
Antelope:

ADD UNIQUE KEY meta_id (meta_id)
ADD PRIMARY KEY (post_id, meta_id)
ADD KEY post_id (post_id, meta_key(32))
ADD KEY meta_key (meta_key(32))
ADD KEY meta_value (meta_value(32))

Also, while this is "correct", I contend that it is "overkill":  ADD UNIQUE KEY meta_id (meta_id)
A simple INDEX would make INSERTs be slightly faster.
(I have  not thought through the case whether Celects might choose the wrong query plan -- as per some other bug report (#4?))

**Comment by rjasdf** [comment]
reopening

**Comment by OllieJones** [comment]
If I could, I'd write `ADD KEY meta_key (meta_key, meta_value(32), post_id)` as `ADD KEY meta_key (meta_key, meta_value(32)) INCLUDES (post_id)` so it could cover  `SELECT post_id FROM wp_postmeta WHERE meta_key = 'foo'` That's why the trailing stuff is there.

**Comment by OllieJones** [comment]
Here's what I have now on wp_postmeta for v1.4.1 The other kv tables have similar keys.

https://github.com/OllieJones/index-wp-mysql-for-speeed/blob/346e367e581c3cac305a4b1679068494170c8688/code/getindexes.php#L71

I changed wp_options to favor the single-row queries over the ```.WHERE autoload='yes'` queries because the single-row queries are far more numerous, the autoload queries don't benefit much from the clustered key, and because large sites avoid the autoload queries via a redis or other cache.

https://github.com/OllieJones/index-wp-mysql-for-speeed/blob/32c452088d65bcd655166f87aa5b96a638667a04/code/getindexes.php#L52
