### ISSUE TITLE
Show on page if active monitor is running

### ISSUE THREAD

**Issue by tripflex** [OllieJones/index-wp-mysql-for-speeed#21]
May be a good idea to show some kind of notification, banner or tag on the page (or in admin bar) when there's a monitor actively running.

While I was working on setting up some tests I did see the notification when it started, but switching between tabs i came back and wasn't sure if it was still running or not (as I was trying to test with Redis disabled).

Might just be good to show "X monitors currently running" or something similar is all ;-) 

Super simple to add to admin bar too:
https://github.com/tripflex/pantheon-env-admin-bar/blob/master/classes/main.php

**Comment by OllieJones** [comment]
Good idea, thanks.

Only one monitor runs at a time, FYI. Probably should give a way to cancel an active monitor, and to prevent starting another one overtop of an active one.

**Comment by OllieJones** [comment]
Nag-banner mentioning in-progress monitor is done for 1.4.5
