### ISSUE TITLE
Remove options, etc, upon uninstallation, not upon deactivation

### ISSUE THREAD

**Issue by OllieJones** [OllieJones/index-wp-mysql-for-speeed#25]
Clean up the plugin's options from uninstall.php, not upon deactivation.

**Comment by hbhalodia** [comment]
Hello @OllieJones,

I hope you are doing well, I want to ask if I can contribute to this issue? If yes, is there any workflow to follow like from which branch I can create the PR and where to raise the PR and whom I have to assign for the review? Thanks.

Regards,
Hit Bhalodia

**Comment by OllieJones** [comment]
Thanks for your offer. You can fork this repo, then issue the PR to the `main` branch. I'll review it. (I'm the sole contributor until your participation.)
