### ISSUE TITLE
Index wp_users on user_display_name

### ISSUE THREAD

**Issue by OllieJones** [OllieJones/index-wp-mysql-for-speeed#4]
Index wp_users on user_display_name
Some end-users want to search by display_name like they do with email or username

**Comment by rjasdf** [comment]
Where is this Search menu?

**Comment by OllieJones** [comment]
This request came from a plugin user with a very large rowcount in wp_users. I can't find the exact request. I think the query is in some plugin or other.

**Comment by rjasdf** [comment]
Should be safe and somewhat easy:  ALTER TABLE wp_users ADD INDEX(display_name)
It would need the 191 kludge for selected versions / charsets.

**Comment by OllieJones** [comment]
Done. For Antelope  `ADD KEY display_name (display_name(32))`

For Barracuda `ADD KEY display_name (display_name)`
