### ISSUE TITLE
postmeta.meta_key default value?

### ISSUE THREAD

**Issue by glagonikas** [OllieJones/index-wp-mysql-for-speeed#41]
I'm running those queries manually because we have already added indexes in the past and i want to avoid messing things up by removing indexes we've previously optimised.

While updating the Primary Key on postmeta, i get this error

<img width="260" alt="image" src="https://user-images.githubusercontent.com/10516403/177201281-ae34a81d-b496-407b-b2bf-8b684f9e63c4.png">

I suspect that's because `meta_key` has a default value of "NULL"?

<img width="854" alt="image" src="https://user-images.githubusercontent.com/10516403/177201321-febc1c8c-1341-47a4-a4a8-601585fa5392.png">

https://github.com/WordPress/WordPress/blob/6.0-branch/wp-admin/includes/schema.php#L153

Do you see any reasons why creating those indexes via the plugin would have a different behaviour and would create the Primary Key?

The same applies to termmeta and usermeta tables, so I'm probably missing something here, or didn't quite understand the indexes that are added...

**Comment by OllieJones** [comment]
The plugin's SQL to convert wp_postmeta's keys from standard to high performance is this.

```sql
ALTER TABLE wp_postmeta
   ADD UNIQUE KEY meta_id (meta_id), 
   DROP PRIMARY KEY, ADD PRIMARY KEY (post_id, meta_key, meta_id), 
   DROP KEY meta_key, ADD KEY meta_key (meta_key, meta_value(32), post_id, meta_id),
   ADD KEY meta_value (meta_value(32), meta_id),
   DROP KEY post_id;
```

When the meta_key column appears in the primary key value, the MariaDB / MySQL software (all versions I've tested) _quietly_ changes the definition of that column from 

```sql
	meta_key VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_unicode_ci'
```

to 

```sql
	meta_key VARCHAR(255) NOT NULL COLLATE 'utf8mb4_unicode_ci',
```

But, if there's a null value in meta_key (disallowed not by WordPress constraints but by convention), the index conversion fails.

Could you help troubleshoot things by doing two things?

* Post the SQL you're using here.
* With the plugin, go to Tools > Index MySQL > About  and upload your metadata.

Thanks.

**Comment by glagonikas** [comment]
I wonder if that's an issue with HeidiSQL rather than MariaDB or the fact I'm running your queries one by one via the SQL client?

We use MariaDB 10.5.16 and there are no null (or empty) meta_keys on any of those tables.

I think the error says that I should manually change the column definition before running the alter table query.

I've not checked if you do this already, but if you know there's a scenario where this fails, maybe it would make sense to check (and report) if the tables have a null value on meta_key before applying those changes, to avoid failing? That would be especially important when/if those get merged into core.

Also, have you got any stats on the value of having this type of PK vs the previous one? So if you were to have all indexes, but leave the PK untouched?

Feel free to close this ticket, as the problem is quite specific and I'm sure I'll find the solution. I just wanted to scratch your brains in case I'm doing something obviously wrong.

**Comment by OllieJones** [comment]
Doing updates via `wp db query "ALTER TABLE whatever"` sets the DBMS connection options to precisely what WordPress uses.  For example, WordPress automatically does this

`SET @@sql_mode := REPLACE(@@sql_mode, 'NO_ZERO_DATE', '');`

to allow reindexing the tables having dates with zero defaults.

Please try using `wp db query "WHATEVER"`. And the latest version of the plugin has `wp index-mysql enable --all --dryrun` to let you inspect the SQL we use.
