### ISSUE TITLE
rework reindexing to be goal-oriented

### ISSUE THREAD

**Issue by OllieJones** [OllieJones/index-wp-mysql-for-speeed#5]
We now have "enable" and "disable", and "reset."  

We need "enable" to go from wherever we are index wise to where the plugin wants us to be.
We need "disable" to go from wherever we are to the WordPress defaults.

And, we need "update" to take us from indexes for old version of plugin to new version (I think).

**Comment by rjasdf** [comment]
What will happen when there is a second "update"?  Maybe "update" should be the update sequence number?

**Comment by rjasdf** [comment]
And, as I commented elsewhere, which "goal" encompasses the plugin changes needed for Antelope to Barracuda?
