### ISSUE TITLE
Strange index names cause syntax errors.

### ISSUE THREAD

**Issue by OllieJones** [OllieJones/index-wp-mysql-for-speeed#50]
MKhalid reports:

My wp_options table is present both in revert key and convert key, and when i try to either convert or revert using the plugin page or wp-cli i get the following error,

“You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ‘UNIQUE, DROP KEY INDEX”

So I did a –dry-run and found the Query and Put it on my workbench still the same error.

ALTER TABLE wp_options ADD UNIQUE KEY option_name (option_name), DROP KEY option_id, DROP KEY UNIQUE, DROP KEY INDEX;

the error goes if i remove “DROP KEY UNIQUE, DROP KEY INDEX” from the query.
So I manually dropped the two indexes “UNIQUE” and “INDEX” using mysql workbench and run the cli command for enabled and it worked successfully.

https://wordpress.org/support/topic/options-table-both-revert-and-convert-and-syntax-error/

**Comment by OllieJones** [comment]
Just reviewing this: `UNIQUE` and `INDEX` are reserved words in the MariaDb / MySQL data definition language. I'll try to work around this, but I strongly suggest avoiding reserved words for naming indexes.

**Comment by rjasdf** [comment]
Would it work to always surround the index name with backticks?  (Unless it is already backtick'd.)

**Comment by OllieJones** [comment]
Table names need backticks, just like index names. https://wordpress.org/support/topic/please-add-backticks-around-table-names-in-queries/


> [ttremain](https://wordpress.org/support/users/ttremain/) (@ttremain)
> [5 days, 7 hours ago](https://wordpress.org/support/topic/please-add-backticks-around-table-names-in-queries/)
> One plug in one of my systems has a hypen in one of the table names.



In the file “code/imsdb.php” lines 686 and 720 needed to be altered to include backticks around the table names.

There may be other places too, but this is all that was caught on my system

**Comment by OllieJones** [comment]
OK.
