### ISSUE TITLE
Feature Request: Add GitHub Plugin URI

### ISSUE THREAD

**Issue by ipajen** [OllieJones/index-wp-mysql-for-speeed#62]
Feature request
If the GitHub Plugin URI would be added on the index-wp-mysql-for-speed plugin it would be so easy to download the latest GitHub version of the plugin with https://github.com/afragen/git-updater to test for example a bug fix.

Thank you!

**Comment by OllieJones** [comment]
Thanks for the suggestion. This was already in readme.txt but I put it into the toplevel php file as well. 
(The directions could be clearer...https://git-updater.com/knowledge-base/required-headers/.)

It will appear in the next release.
