### ISSUE TITLE
PHP 8.2 Deprecated warnings

### ISSUE THREAD

**Issue by ipajen** [OllieJones/index-wp-mysql-for-speeed#63]
latest main code. MySQL:10.4.29-MariaDB WordPress:6.3-beta4 php:8.2.5

Deprecated	Creation of dynamic property Imfs_AdminPageFramework_Form_admin_page::$aSections is deprecated	
wp-content/plugins/index-wp-mysql-for-speed/afp/factory/admin_page/AdminPageFramework.php:85

Deprecated	Creation of dynamic property ImfsDb::$tableFormats is deprecated	
wp-content/plugins/index-wp-mysql-for-speed/code/imsfdb.php:53

Deprecated	Creation of dynamic property ImfsPage::$pluginUpgrading is deprecated	
wp-content/plugins/index-wp-mysql-for-speed/code/admin.php:394

Deprecated	Creation of dynamic property Imfs_AdminPageFramework_TabNavigationBar::$aActiveSlugs is deprecated	
wp-content/plugins/index-wp-mysql-for-speed/afp/factory/_common/_abstract/_view/AdminPageFramework_TabNavigationBar.php:16

Deprecated	strip_tags(): Passing null to parameter #1 ($string) of type string is deprecated	
wp-content/plugins/index-wp-mysql-for-speed/afp/factory/_common/form/_view/sectionset/AdminPageFramework_Form_View___FieldTitle.php:33

Deprecated	explode(): Passing null to parameter #2 ($string) of type string is deprecated	
wp-content/plugins/index-wp-mysql-for-speed/afp/factory/_common/utility/base_utility/AdminPageFramework_Utility.php:570

**Comment by OllieJones** [comment]
Fixed in 1.4.14.
