### ISSUE TITLE
PHP 8.3 deprecated warning get_class()

### ISSUE THREAD

**Issue by ipajen** [OllieJones/index-wp-mysql-for-speeed#65]
### Environment
- WordPress: 6.3-RC3
- PHP: 8.3.0beta2
- Server: Apache/2.4.54 (Win64) PHP/8.3.0beta2 mod_fcgid/2.3.10-dev
- Database: mysqli (Server: 8.0.31 / Client: mysqlnd 8.3.0beta2)
- Browser: Edge 115.0.1901.188 (Windows 10/11)
- Latest main code from github for index-wp-mysql-for-speed

`Deprecated	Calling get_class() without arguments is deprecated	
wp-content/plugins/index-wp-mysql-for-speed-2f15cb4144129aea6b7e2ddff9e439c5a6518372/afp/factory/_common/utility/wp_utility/AdminPageFramework_WPUtility.php:261

Deprecated	Calling get_class() without arguments is deprecated	
wp-content/plugins/index-wp-mysql-for-speed-2f15cb4144129aea6b7e2ddff9e439c5a6518372/afp/factory/_common/_abstract/_controller/AdminPageFramework_Resource_Base.php:152

Deprecated	Calling get_class() without arguments is deprecated	
wp-content/plugins/index-wp-mysql-for-speed-2f15cb4144129aea6b7e2ddff9e439c5a6518372/afp/factory/_common/utility/wp_utility/AdminPageFramework_WPUtility.php:289

Deprecated	Calling get_class() without arguments is deprecated	
wp-content/plugins/index-wp-mysql-for-speed-2f15cb4144129aea6b7e2ddff9e439c5a6518372/afp/factory/_common/_abstract/_controller/AdminPageFramework_Resource_Base.php:160

`

**Comment by OllieJones** [comment]
Thanks for this. It looks like, inside a static method, `get_class()` can be replaced with `static::class`.
