### ISSUE TITLE
Small enchantment links

### ISSUE THREAD

**Issue by ipajen** [OllieJones/index-wp-mysql-for-speeed#67]
Following links has redirects and can be updated to avoid redirects in the [index-wp-mysql-for-speed] plugin.

http://en.michaeluno.jp/admin-page-framework 302,301,302, 200
https://plumislandmedia.net/index-wp-mysql-for-speed/	301,200
https://plumislandmedia.net/index-wp-mysql-for-speed/tables_and_keys/ 301,200
https://plumislandmedia.net/index-wp-mysql-for-speed/monitor 301,200

**Comment by OllieJones** [comment]
Thanks. At least some of these are fixed in 1.4.14.

**Comment by ipajen** [comment]
> Thanks. At least some of these are fixed in 1.4.14.

Your welcome. Also the https://plumislandmedia.net redirects to https://www.plumislandmedia.net
The props are wrong. @ipajen  not @ipagen.  ;) Thank you!
